### ISSUE TITLE
Minimal version of Stage/Scene/SceneGraph

### ISSUE THREAD

**Issue by romanarust** [compas-dev/compas_xr#4]
As a `user`, I need a class that contains layers, materials, lights, cameras, and geometry that is easily convertable to USD or GLTF.

This issue's scope is to build a minimal prototype of the scene graph that would eventually be upstreamed to compas core. Main idea to keep in focus is to build it light and not aim for feature completeness, but still keep in mind the desired long term structure we want to get to.

**Comment by gonzalocasas** [comment]
Maybe relevant here: https://pypi.org/project/usd-core

**Comment by romanarust** [comment]
Scene version already implemented
